server:
  port: 8090

eureka:
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
        default-zone: http://localhost:8761/eureka
  instance:
     hostname: localhost
spring:
  cloud:
     gateway:
        discovery:
          locator:
             enabled: true
        routes:
              - id: service-customers
                uri: lb://service-customers
                predicates:
                 - Path=/customerPerson/** ,/customerEnterprise/**
                filters:
                 - StripPrefix=0
              - id: service-product-businesscredit
                uri: lb://service-product-businesscredit
                predicates:
                 - Path=/businessCredit/**
                filters:
                 - StripPrefix=1
              - id: service-product-currentaccount
                uri: lb://service-product-currentaccount
                predicates:
                 - Path=/currentAccount/**
                filters:
                 - StripPrefix=1
              - id: service-product-fixedtermaccount
                uri: lb://service-product-fixedtermaccount
                predicates:
                 - Path=/fixedTermAccount/**
                filters:
                 - StripPrefix=1
              - id: service-product-fixedtermaccount
                uri: lb://service-product-fixedtermaccount
                predicates:
                 - Path=/fixedTermAccount/**
                filters:
                 - StripPrefix=1
              - id: service-product-personalcredit
                uri: lb://service-product-personalcredit
                predicates:
                 - Path=/personalCredit/**
                filters:
                 - StripPrefix=1
              - id: service-product-savingaccount
                uri: lb://service-product-savingaccount
                predicates:
                 - Path=/savingAccount/**
                filters:
                 - StripPrefix=1
              - id: service-transaction-enterprise
                uri: lb://service-transaction-enterprise
                predicates:
                 - Path=/transactionEnterprise/**
                filters:
                 - StripPrefix=1
              - id: service-transaction-person
                uri: lb://service-transaction-person
                predicates:
                 - Path=/transactionPerson/**
                filters:
                 - StripPrefix=1





