server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  data:
    mongodb:
        uri: mongodb+srv://user:omarlazopassword@clusterbootcamp.28gww.mongodb.net/db_product_currentaccount?retryWrites=true&w=majority
eureka:
  client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
        default-zone: http://localhost:8900/eureka
  instance:
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}