server:
  port: 8050

spring:
  data:
    mongodb:
      uri: mongodb+srv://user:omarlazopassword@clusterbootcamp.28gww.mongodb.net/db_rate_bootcoin?retryWrites=true&w=majority
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
            
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/